### ISSUE TITLE
Upgrade to Node.js 20/npm 10

### ISSUE THREAD

**Issue by mslinnea** [alleyinteractive/apple-music#78]
### Description

The current version of the Apple Music WordPress plugin uses an outdated node version. We should upgrade to Node.js 20 and npm 10 in order to keep current.

**Acceptance Criteria**
- The plugin builds and runs successfully with Node.js 20 and npm 10
- The node version is specified in package.json.
- All existing functionality continues to work after upgrade
- The upgrade does not introduce any new bugs or issues
- Tests pass after upgrading
- The upgrade is backwards compatible with sites running the current plugin version or breaking changes are documented

### Use Case

- Match WordPress versions
- Node.js 20 has improved performance and supports more modern JavaScript features compared to Node.js 16. Upgrading will allow us to use newer language capabilities.
- npm 10 has several bug fixes and improvements over npm 8. Upgrading will resolve bugs and improve reliability.
- Keeping up with current Node.js and npm versions allows us to take advantage of performance improvements and new features. It also ensures continued compatibility with other modern tools and packages.

**Comment by kevinfodness** [comment]
This plugin is no longer being maintained, so I'm going to archive the repo.
